name: setup

description: setup

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"
        cache: npm

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Install packages
      run: | 
        npm install
        npm run init
      shell: bash

    - name: Compile
      run: npm run compile
      shell: bash

